export const FETCHING_TASKS = 'FETCHING_TASKS'
export const FETCHING_TASKS_DONE = 'FETCHING_TASKS_DONE'
export const FETCHING_TASKS_ERROR = 'FETCHING_TASKS_ERROR'
export const ADDING_NEW_TASK = 'ADDING_NEW_TASK'